# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

# - task: SonatypeCloudPipelineTask@0
#   inputs:
#     SonatypeCloudService: 'Sonatype Cloud - Maury''s Key'
#     stage: 'Build'

- task: JavaToolInstaller@0
  inputs:
    versionSpec: '17' 
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'PreInstalled'

- task: NexusIqPipelineTask@1
  inputs:
    nexusIqService: 'iq.bwhyte.ngrok.io'
    applicationId: 'Struts2-rce'
    stage: 'stage-release'